services:
  app:
    build: ./app/
    container_name: node_app
    environment:
      MONGO_URI: ${ secrets.CONNECTION_STRING }
      DEEPSEEK_API_KEY: ${ secrets.DEEPSEEK_API_KEY }
      DEEPSEEK_API_URL: ${ secrets.DEEPSEEK_API_URL }
      OPENAI_API_KEY: ${ secrets.OPENAI_API_KEY }
      OPENAI_API_URI: ${ secrets.OPENAI_API_URI }
      TELEGRAM_TOKEN: ${ secrets.TELEGRAM_TOKEN }
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ MONGO_INITDB_ROOT_USERNAME }
      MONGO_INITDB_ROOT_PASSWORD: ${ MONGO_INITDB_ROOT_PASSWORD }
      MONGO_INITDB_DATABASE: ${ MONGO_INITDB_DATABASE }
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
