name: Main

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # App .env
      MONGO_URI: ${{ secrets.CONNECTION_STRING }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_URI: ${{ secrets.OPENAI_API_URI }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      # DB .env
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}

    strategy:
      matrix:
        # node_version: ['22', '20', '18']
        node_version: ['latest']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3      
      
    - name: Create MongoDB
      run: docker compose up mongo -d --build

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}  
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test

  docker:
    needs: test
    uses: ./.github/workflows/Docker.yml
    secrets: inherit